In [1]:
from sklearn.base import BaseEstimator

In [2]:
class MydummyClassifier(BaseEstimator):
    def fit(self, X, y= None):
        pass
    
def predict(self,X):
    pred = np.zeros((X.Shape[0],1))
    for i in range(X.shape[0]):
        if x['Sex'].iloc[i] == 1:
            pred[i] = 0
        else:
            pred[i] = 1
            
    return pred

In [3]:
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [4]:
class MyFakeClassifier(BaseEstimator):
    def fit(self, X, y):
        pass

    def predict(self, X):
        return np.zeros((len(X),1), dtype = bool)

In [5]:
digits = fetch_openml('mnist_784', version = 1)

In [6]:
y = (digits.target == '7').astype(int)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, y, random_state = 11)

In [8]:
print('레이블 테스트 세트 크기 :', y_test.shape)
print('테스트 세트 레이블 0 과 1의 분포도 :\n', pd.Series(y_test).value_counts())


레이블 테스트 세트 크기 : (17500,)
테스트 세트 레이블 0 과 1의 분포도 :
 0    15667
1     1833
dtype: int64


In [9]:
fakeclf = MyFakeClassifier()
fakeclf.fit(X_train, y_train)

In [10]:
fakepred = fakeclf.predict(X_test)

In [11]:
print('모든 예측을 0으로 해도 나오는 정확도는 : {0:.3f}'.format(accuracy_score(fakepred, y_test)))

모든 예측을 0으로 해도 나오는 정확도는 : 0.895


In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
confusion_matrix(fakepred, y_test)

array([[15667,  1833],
       [    0,     0]], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    print('오차 행렬')
    print(confusion)
    print('정확도 : {0:.4f}, 정밀도 : {1:.4f}, 재현율 : {2:.4f}'.format(accuracy, precision, recall))

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
def fillna(df):
    df['Age'].fillna(df['Age'].mean(), inplace = True)
    df['Cabin'].fillna('N', inplace = True)
    df['Embarked'].fillna('N', inplace = True)
    df['Fare'].fillna(0, inplace = True)
    return df

def drop_features(df):
    df.drop(['PassengerId', 'Name', 'Ticket'], axis = 1 , inplace = True)
    return df

def format_features(df):
    df['Cabin'] = df['Cabin'].str[:1]
    features = ['Cabin', 'Sex', 'Embarked']
    for feature in features:
        le = LabelEncoder()
        le = le.fit(df[feature])
        df[feature] = le.transform(df[feature])
        
    return df


def transform_features(df):
    df = fillna(df)
    df = drop_features(df)
    df = format_features(df)
    return df

In [24]:
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived', axis = 1)
X_titanic_df = transform_features(X_titanic_df)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X_titanic_df, y_titanic_df, test_size = 0.2, random_state = 11)

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
lr_clf = LogisticRegression()

In [31]:
lr_clf.fit(X_train, y_train)

C:\Users\msi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [32]:
pred = lr_clf.predict(X_test)

In [33]:
get_clf_eval(y_test,pred)

오차 행렬
[[104  14]
 [ 13  48]]
정확도 : 0.8492, 정밀도 : 0.7742, 재현율 : 0.7869


In [34]:
pred_proba = lr_clf.predict_proba(X_test)
pred = lr_clf.predict(X_test)
print('pred_proba()결과 shape : {0}'.format(pred_proba.shape))
print('pred_proba array에서 앞 3개만 샘플로 추출 \n : ', pred_proba[:3])

pred_proba()결과 shape : (179, 2)
pred_proba array에서 앞 3개만 샘플로 추출 
 :  [[0.46196064 0.53803936]
 [0.87860795 0.12139205]
 [0.87714215 0.12285785]]


In [36]:
pred_proba

array([[0.46196064, 0.53803936],
       [0.87860795, 0.12139205],
       [0.87714215, 0.12285785],
       [0.88265446, 0.11734554],
       [0.85532615, 0.14467385],
       [0.8822094 , 0.1177906 ],
       [0.88835753, 0.11164247],
       [0.20894318, 0.79105682],
       [0.78293618, 0.21706382],
       [0.36934246, 0.63065754],
       [0.89978874, 0.10021126],
       [0.87500056, 0.12499944],
       [0.87713606, 0.12286394],
       [0.8883108 , 0.1116892 ],
       [0.4365136 , 0.5634864 ],
       [0.85890466, 0.14109534],
       [0.90374854, 0.09625146],
       [0.73341056, 0.26658944],
       [0.72480075, 0.27519925],
       [0.17179312, 0.82820688],
       [0.75359271, 0.24640729],
       [0.61919607, 0.38080393],
       [0.85453876, 0.14546124],
       [0.81483216, 0.18516784],
       [0.88793336, 0.11206664],
       [0.76551877, 0.23448123],
       [0.85964939, 0.14035061],
       [0.9258068 , 0.0741932 ],
       [0.71958361, 0.28041639],
       [0.69552911, 0.30447089],
       [0.

In [37]:
from sklearn.preprocessing import Binarizer

In [56]:
custom_threshold = 0.6

pred_proba_1 = pred_proba[:,1].reshape(-1,1)

binarizer = Binarizer(threshold = custom_threshold).fit(pred_proba_1)
custom_predict = binarizer.transform(pred_proba_1)

get_clf_eval(y_test, custom_predict)

오차 행렬
[[112   6]
 [ 16  45]]
정확도 : 0.8771, 정밀도 : 0.8824, 재현율 : 0.7377


In [61]:
thresholds = [0.4, 0.45, 0.5, 0.55, 0.6]

def get_eval_by_threshold(y_test, pred_proba_1, thresholds):
    for custom_threshold in thresholds:
        binarizer = Binarizer(threshold = custom_threshold).fit(pred_proba_1)
        custom_predict = binarizer.transform(pred_proba_1)
        
        print('threshold 값이 {0}일 때  :\n'.format(custom_threshold))
        get_clf_eval(y_test, custom_predict)
        print('\n\n')

In [62]:
get_eval_by_threshold(y_test, pred_proba_1, thresholds)

threshold 값이 0.4일 때  :

오차 행렬
[[98 20]
 [10 51]]
정확도 : 0.8324, 정밀도 : 0.7183, 재현율 : 0.8361



threshold 값이 0.45일 때  :

오차 행렬
[[103  15]
 [ 12  49]]
정확도 : 0.8492, 정밀도 : 0.7656, 재현율 : 0.8033



threshold 값이 0.5일 때  :

오차 행렬
[[104  14]
 [ 13  48]]
정확도 : 0.8492, 정밀도 : 0.7742, 재현율 : 0.7869



threshold 값이 0.55일 때  :

오차 행렬
[[109   9]
 [ 15  46]]
정확도 : 0.8659, 정밀도 : 0.8364, 재현율 : 0.7541



threshold 값이 0.6일 때  :

오차 행렬
[[112   6]
 [ 16  45]]
정확도 : 0.8771, 정밀도 : 0.8824, 재현율 : 0.7377





In [63]:
from sklearn.metrics import precision_recall_curve

In [65]:
pred_proba_class1 = lr_clf.predict_proba(X_test)[:, 1]
precisions, recalls, thresholds = precision_recall_curve(y_test, pred_proba_class1)
print('반환된 분류 결정 임곗값 배열의 Shape:', thresholds.shape)

thr_index = np.arange(0, thresholds.shape[0], 15)


반환된 분류 결정 임곗값 배열의 Shape: (143,)


In [68]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
%matplotlib inline

In [69]:
from sklearn.metrics import f1_score

In [72]:
f1 = f1_score(y_test, pred)
f1

0.7804878048780488